#!/usr/bin/perl
use lib 'lib';
use Lingua::EN::Words2Nums;
$Lingua::EN::Words2Nums::debug=1;
if (@ARGV) {
	print "$ARGV[0] => ".words2nums(shift)."\n";
}
else {
	while (<>) {
		print "$_ => ".words2nums($_)."\n";
	}
}
